// <auto-generated />
using System;
using FxEdge.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FxEdge.DataAccess.Migrations
{
    [DbContext(typeof(FxEdgeDbContext))]
    partial class FxEdgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FxEdge.Business.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Formula1M")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Formula1W")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Formula1Y")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Formula3M")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "EntryAtUtc");

                    b.ToTable("Entries", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.EntryDailyCandle", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CloseAtr")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstExtreme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpenAtr")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "DayIndex");

                    b.ToTable("EntryDailyCandles", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.EntryFundamentalFeatureSnapshot", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseActualVsForecast")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseActualVsPrevious")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BaseAnnouncementAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseForecastValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseNormalizedValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BasePreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Difference")
                        .HasColumnType("TEXT");

                    b.Property<int>("Polarity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("QuoteActualVsForecast")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteActualVsPrevious")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuoteAnnouncementAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteForecastValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteNormalizedValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuotePreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteValue")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "Feature");

                    b.ToTable("EntryFundamentalFeatureSnapshots", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.EntryResult", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horizon")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstExtremeReached")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaximumAdverseExcursionAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaximumFavorableExcursionAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnAtHorizonEndAtr")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "Horizon");

                    b.ToTable("EntryResults", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.EntryTechnicalFeatureSnapshot", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "Feature");

                    b.ToTable("EntryTechnicalFeatureSnapshots", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.FundamentalObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnnouncementAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ForecastValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Currency", "Feature", "AnnouncementAtUtc")
                        .IsUnique();

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntrySpacingAtr")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverallStopLossAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfitPerEntryAtr")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Strategies", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.StrategySimulation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LossAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdownAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitAtr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulEntries")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinRatePercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "Horizon");

                    b.ToTable("StrategySimulations", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.StrategySimulationEntryOutcome", b =>
                {
                    b.Property<Guid>("StrategySimulationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ResultAtr")
                        .HasColumnType("TEXT");

                    b.HasKey("StrategySimulationId", "EntryId");

                    b.ToTable("StrategySimulationEntryOutcomes", (string)null);
                });

            modelBuilder.Entity("FxEdge.Business.Entities.EntryFundamentalFeatureSnapshot", b =>
                {
                    b.HasOne("FxEdge.Business.Entities.Entry", null)
                        .WithMany("FundamentalSnapshot")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FxEdge.Business.Entities.EntryTechnicalFeatureSnapshot", b =>
                {
                    b.HasOne("FxEdge.Business.Entities.Entry", null)
                        .WithMany("TechnicalSnapshot")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FxEdge.Business.Entities.StrategySimulationEntryOutcome", b =>
                {
                    b.HasOne("FxEdge.Business.Entities.StrategySimulation", null)
                        .WithMany("EntryOutcomes")
                        .HasForeignKey("StrategySimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FxEdge.Business.Entities.Entry", b =>
                {
                    b.Navigation("FundamentalSnapshot");

                    b.Navigation("TechnicalSnapshot");
                });

            modelBuilder.Entity("FxEdge.Business.Entities.StrategySimulation", b =>
                {
                    b.Navigation("EntryOutcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
