using FxEdge.Business.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FxEdge.DataAccess.Configurations;

/// <summary>
/// Maps Entry to the "Entries" table, plus its two owned collections
/// (FundamentalSnapshot, TechnicalSnapshot) which are mapped through their own
/// IEntityTypeConfiguration classes. Entry exposes those collections only as
/// IReadOnlyList&lt;T&gt; backed by private List&lt;T&gt; fields, so EF Core is told to use the
/// backing field directly rather than the (read-only) public property.
/// </summary>
public sealed class EntryConfiguration : IEntityTypeConfiguration<Entry>
{
    public void Configure(EntityTypeBuilder<Entry> builder)
    {
        builder.ToTable("Entries");

        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id)
            .ValueGeneratedNever(); // Guid is always generated by the application, never by the database.

        builder.Property(e => e.BaseCurrency)
            .HasConversion<string>()
            .HasMaxLength(3)
            .IsRequired();

        builder.Property(e => e.QuoteCurrency)
            .HasConversion<string>()
            .HasMaxLength(3)
            .IsRequired();

        builder.Property(e => e.EntryAtUtc)
            .HasConversion(UtcDateTimeConverters.NonNullable)
            .IsRequired();

        builder.Property(e => e.EntryPrice)
            .IsRequired();

        builder.Property(e => e.Direction)
            .HasConversion<string>()
            .HasMaxLength(8)
            .IsRequired();

        builder.Property(e => e.Formula1W);
        builder.Property(e => e.Formula1M);
        builder.Property(e => e.Formula3M);
        builder.Property(e => e.Formula1Y);

        // CurrencyPair is a computed value object (validated Base/Quote), never persisted.
        builder.Ignore(e => e.Pair);

        builder.HasMany(e => e.FundamentalSnapshot)
            .WithOne()
            .HasForeignKey(s => s.EntryId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(e => e.FundamentalSnapshot)
            .UsePropertyAccessMode(PropertyAccessMode.Field);

        builder.HasMany(e => e.TechnicalSnapshot)
            .WithOne()
            .HasForeignKey(s => s.EntryId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(e => e.TechnicalSnapshot)
            .UsePropertyAccessMode(PropertyAccessMode.Field);

        // Not unique - unlike Observations, two Entries for the same pair at the same
        // timestamp are not a "duplicate publication", just an index for filtering.
        builder.HasIndex(e => new { e.BaseCurrency, e.QuoteCurrency, e.EntryAtUtc });
    }
}
