using FxEdge.Business.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FxEdge.DataAccess.Configurations;

/// <summary>
/// Maps FundamentalObservation to the "Observations" table. Keeps EF Core specifics
/// (conversions, indexes) entirely out of the Business entity itself (Fluent API only,
/// no EF attributes on the domain class).
/// </summary>
public sealed class FundamentalObservationConfiguration : IEntityTypeConfiguration<FundamentalObservation>
{
    public void Configure(EntityTypeBuilder<FundamentalObservation> builder)
    {
        builder.ToTable("Observations");

        builder.HasKey(o => o.Id);
        builder.Property(o => o.Id)
            .ValueGeneratedNever(); // Guid is always generated by the application, never by the database.

        builder.Property(o => o.Currency)
            .HasConversion<string>()
            .HasMaxLength(3)
            .IsRequired();

        builder.Property(o => o.Feature)
            .HasConversion<string>()
            .HasMaxLength(64)
            .IsRequired();

        builder.Property(o => o.AnnouncementAtUtc)
            .HasConversion(UtcDateTimeConverters.NonNullable)
            .IsRequired();

        // Nullable: some features genuinely never have a published market forecast.
        // No .IsRequired() call here - that would force NOT NULL at the DB level,
        // contradicting the CLR decimal? type EF Core already maps as nullable by convention.
        builder.Property(o => o.ForecastValue);

        builder.Property(o => o.Value)
            .IsRequired();

        // Prevents two observations for the same currency+feature at the exact same
        // announcement timestamp - the same duplicate rule ObservationService enforces
        // at the application layer, backstopped here at the database layer.
        builder.HasIndex(o => new { o.Currency, o.Feature, o.AnnouncementAtUtc })
            .IsUnique();
    }
}
