using FxEdge.Business.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FxEdge.DataAccess.Configurations;

/// <summary>
/// Maps Strategy to the "Strategies" table.
/// </summary>
public sealed class StrategyConfiguration : IEntityTypeConfiguration<Strategy>
{
    public void Configure(EntityTypeBuilder<Strategy> builder)
    {
        builder.ToTable("Strategies");

        builder.HasKey(s => s.Id);
        builder.Property(s => s.Id)
            .ValueGeneratedNever(); // Guid is always generated by the application, never by the database.

        builder.Property(s => s.Name)
            .HasMaxLength(200)
            .IsRequired();

        builder.Property(s => s.EntrySpacingAtr).IsRequired();
        builder.Property(s => s.TakeProfitPerEntryAtr).IsRequired();
        builder.Property(s => s.OverallStopLossAtr).IsRequired();
        builder.Property(s => s.MaxEntries).IsRequired();
    }
}
