using FxEdge.Business.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FxEdge.DataAccess.Configurations;

/// <summary>
/// Maps StrategySimulation to the "StrategySimulations" table, plus its owned
/// EntryOutcomes collection (mapped via its own IEntityTypeConfiguration). Same
/// backing-field navigation pattern as EntryConfiguration, since EntryOutcomes is
/// exposed only as IReadOnlyList&lt;T&gt;.
/// </summary>
public sealed class StrategySimulationConfiguration : IEntityTypeConfiguration<StrategySimulation>
{
    public void Configure(EntityTypeBuilder<StrategySimulation> builder)
    {
        builder.ToTable("StrategySimulations");

        builder.HasKey(s => s.Id);
        builder.Property(s => s.Id)
            .ValueGeneratedNever(); // Guid is always generated by the application, never by the database.

        builder.Property(s => s.StrategyId).IsRequired();

        builder.Property(s => s.Horizon)
            .HasConversion<string>()
            .HasMaxLength(16)
            .IsRequired();

        builder.Property(s => s.RunAtUtc)
            .HasConversion(UtcDateTimeConverters.NonNullable)
            .IsRequired();

        builder.Property(s => s.ProfitAtr).IsRequired();
        builder.Property(s => s.LossAtr).IsRequired();
        builder.Property(s => s.SuccessfulEntries).IsRequired();
        builder.Property(s => s.FailedEntries).IsRequired();
        builder.Property(s => s.WinRatePercent).IsRequired();
        builder.Property(s => s.MaxDrawdownAtr).IsRequired();

        builder.HasMany(s => s.EntryOutcomes)
            .WithOne()
            .HasForeignKey(o => o.StrategySimulationId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(s => s.EntryOutcomes)
            .UsePropertyAccessMode(PropertyAccessMode.Field);

        builder.HasIndex(s => new { s.StrategyId, s.Horizon });
    }
}
